import { ref, computed } from "vue";
import { defineStore } from "pinia";
import { addPointToFirebase } from "../firebase/firebaseService";

export const useSummaryStore = defineStore("summaryStore", {
  state: () => ({
    totalPointsWonPlayer1: 0,
    totalPointsWonPlayer2: 0,
    totalPointsPlayer1: 0,
    totalPointsPlayer2: 0,
    totalPointWonPercentagePlayer1: 0,
    totalPointWonPercentagePlayer2: 0,
    unforcedErrorsPlayer1: 0,
    unforcedErrorsPlayer2: 0,
    forcedErrorsPlayer1: 0,
    forcedErrorsPlayer2: 0,
    firstServePercentagePlayer1: 0,
    firstServePercentagePlayer2: 0,
    firstServeWonCountPlayer1: 0,
    firstServeWonCountPlayer2: 0,
    firstServeCountPlayer1: 0,
    firstServeCountPlayer2: 0,
    firstServeWonPercentagePlayer1: 0,
    firstServeWonPercentagePlayer2: 0,
    secondServeWonCountPlayer1: 0,
    secondServeWonCountPlayer2: 0,
    secondServeCountPlayer1: 0,
    secondServeCountPlayer2: 0,
    secondServeWonPercentagePlayer1: 0,
    secondServeWonPercentagePlayer2: 0,
    pointsWonServedTPlayer1: 0,
    pointsWonServedTPlayer2: 0,
    pointsServedTPlayer1: 0,
    pointsServedTPlayer2: 0,
    pointsWonServedBodyBackhandPlayer1: 0,
    pointsWonServedBodyBackhandPlayer2: 0,
    pointsServedBodyBackhandPlayer1: 0,
    pointsServedBodyBackhandPlayer2: 0,
    pointsWonServedBodyForehandPlayer1: 0,
    pointsWonServedBodyForehandPlayer2: 0,
    pointsServedBodyForehandPlayer1: 0,
    pointsServedBodyForehandPlayer2: 0,
    pointsWonServedWidePlayer1: 0,
    pointsWonServedWidePlayer2: 0,
    pointsServedWidePlayer1: 0,
    pointsServedWidePlayer2: 0,
    totalReturnsInPlayer1: 0,
    totalReturnsInPlayer2: 0,
    totalReturnsPlayer1: 0,
    totalReturnsPlayer2: 0,
    totalReturnPointsWonPlayer1: 0,
    totalReturnPointsWonPlayer2: 0,
    returnPointsWonPercentagePlayer1: 0,
    returnPointsWonPercentagePlayer2: 0,
    returnsInPercentagePlayer1: 0,
    returnsInPercentagePlayer2: 0,
    returnErrorsWidePlayer1: 0,
    returnErrorsWidePlayer2: 0,
    returnErrorsBodyBackhandPlayer1: 0,
    returnErrorsBodyBackhandPlayer2: 0,
    returnErrorsBodyForehandPlayer1: 0,
    returnErrorsBodyForehandPlayer2: 0,
    returnErrorsTPlayer1: 0,
    returnErrorsTPlayer2: 0,
    totalReturnErrorsPlayer1: 0,
    totalReturnErrorsPlayer2: 0,
    totalErrorsNetPlayer1: 0,
    totalErrorsNetPlayer2: 0,
    totalErrorsLongPlayer1: 0,
    totalErrorsLongPlayer2: 0,
    totalErrorsWidePlayer1: 0,
    totalErrorsWidePlayer2: 0,
    rallyLength1_5WonPlayer1: 0,
    rallyLength1_5WonPlayer2: 0,
    rallyLength1_5Player1: 0,
    rallyLength1_5Player2: 0,
    rallyLength6_10WonPlayer1: 0,
    rallyLength6_10WonPlayer2: 0,
    rallyLength6_10Player1: 0,
    rallyLength6_10Player2: 0,
    rallyLength11_15WonPlayer1: 0,
    rallyLength11_15WonPlayer2: 0,
    rallyLength11_15Player1: 0,
    rallyLength11_15Player2: 0,
    rallyLength16plusWonPlayer1: 0,
    rallyLength16plusWonPlayer2: 0,
    rallyLength16plusPlayer1: 0,
    rallyLength16plusPlayer2: 0,

    deucePoints: 0,
    deucePointsWonPlayer1: 0,
    deucePointsWonPlayer2: 0,

    countPlayer1First: 0,
    intentPlayer1First: "",
    strokeSidePlayer1First: "",
    strokeTypePlayer1First: "",
    errorLocationPlayer1First: "",

    countPlayer1Second: 0,
    intentPlayer1Second: "",
    strokeSidePlayer1Second: "",
    strokeTypePlayer1Second: "",
    errorLocationPlayer1Second: "",

    countPlayer2First: 0,
    intentPlayer2First: "",
    strokeSidePlayer2First: "",
    strokeTypePlayer2First: "",
    errorLocationPlayer2First: "",

    countPlayer2Second: 0,
    intentPlayer2Second: "",
    strokeSidePlayer2Second: "",
    strokeTypePlayer2Second: "",
    errorLocationPlayer2Second: "",
  }),
  getters: {},
  actions: {},
});
